### ISSUE TITLE
Разработка микросервиса обучения

### ISSUE THREAD

**Issue by MAKAR1031** [tamagochy/tamagotchi#11]
Репозиторий: https://github.com/tamagochy/tamagotchi-training

**Comment by palicpiotr** [comment]
1. Проект создан
2. Проект сконфигурирован
3. Подготовлен

**Comment by palicpiotr** [comment]
4. Добавлю Swagger
5. Нужно будет подумать о хранилище и о дальнейшей работе

**Comment by MAKAR1031** [comment]
Пока приостанавливаем разработку. Необходимо дождаться уточнения по аналитике, возможно обучение станет частью базовой механики.

**Comment by MAKAR1031** [comment]
Задача неактуальна
