### ISSUE TITLE
BasicMechanics Некорректное время сравнения

### ISSUE THREAD

**Issue by Keyn96** [tamagochy/tamagotchi#20]
Шаги воспроизведения: 
1. Отправить запрос к сервису Базовая механика методу feed, причем текущее локальное время = 21:00
Ожидаемый результат:
Показатель Rest снижается до 25.

Результат фактический:
Показатель не снижается, предположительно из-за того, что время базы данных отстает на 3 часа от локального.

**Comment by MAKAR1031** [comment]
Думаю, что проблема в настройке окружения.
Необходимо проверить системное время в контейнере. При необходимости настроить его таким образом, чтобы оно совпадало с локальным.

**Comment by MAKAR1031** [comment]
Для того, чтобы настроить таймзону в контейнере, необходимо добавить переменную окружения для соответствующего контейнера: `TZ: Europe/Moscow`

**Comment by Keyn96** [comment]
Вопрос - как ее добавить?

**Comment by Keyn96** [comment]
Локальное время добавлено
