### ISSUE TITLE
BasicMechanics Неправильный возврат ошибки

### ISSUE THREAD

**Issue by Keyn96** [tamagochy/tamagotchi#21]
Шаги воспроизведения:
Отправить запрос к сервису Базовая механика методу play c action = "not action"
Ожидаемый результат:
{
    errors: [
        {
            "attr":"action",
            "code":"validation.Incorrect"
        }
    ]
}
Результат фактический:
{
    "errors": [
        {
            "code": "protocol.Incorrect"
        }
    ]
}

**Comment by MAKAR1031** [comment]
Исправлено в 1.0.2.master.1f61b23.46

**Comment by Keyn96** [comment]
Баг отсутствует теперь
