### ISSUE TITLE
МкС Authorization. Некорректная ошибка при пустом login

### ISSUE THREAD

**Issue by Ceparator** [tamagochy/tamagotchi#27]
Не передать в запросе login или password

Ожидаемый результат:
validation.Missing

Фактический результат:
{
    "errors": [
        {
            "code": "business.UserNotFound"
        }
    ]
}

**Comment by itine** [comment]
![image](https://user-images.githubusercontent.com/16553609/49399020-25991080-f751-11e8-8f49-22445a30c803.png)
![image](https://user-images.githubusercontent.com/16553609/49399175-a2c48580-f751-11e8-9909-550e9a373d21.png)
все ок вроде

**Comment by Ceparator** [comment]
Проверено
