### ISSUE TITLE
МкС Authorization. Отсутствует проверка на существующий логин в БД

### ISSUE THREAD

**Issue by Ceparator** [tamagochy/tamagotchi#29]
Отправить 2 запроса к registration, передав одинаковы логин, но разный email

ОР:
"code": "business.UserAlreadyExists"

ФР:
Успешная регистрация пользователя с таким же логином

**Comment by itine** [comment]
![image](https://user-images.githubusercontent.com/16553609/49398716-42811400-f750-11e8-8b2c-70a72326be43.png)
я не нашел бага

**Comment by itine** [comment]
1.1.3 fixed

**Comment by Ceparator** [comment]
Проверено
