### ISSUE TITLE
МкС Authorization. Различные названия полей в таблице CONFIRMATION_CODES

### ISSUE THREAD

**Issue by Ceparator** [tamagochy/tamagotchi#31]
В доке название полей в описании метода restoreAccess:
USERS_ID	
VALUE	
CREATION_TIME
ACTIVE

В описании таблицы снизу в доке:
USER_ID

В реализации:
UserId
CodeValue	
CreationTime
Active

Как корректно ?

**Comment by itine** [comment]
я бы оставил второй вариант, так как в коде МкСа атрибуты сущностей странно видеть в формате "XYZ_A"

**Comment by dyshechka** [comment]
Странно, что раньше этим вопросом никто не задавался)

Тут явно присутствует некое недопонимание использования различных стилей написания составных слов.

- Использование SCREAMING_SNAKE_CASE указывает на то, что идет взаимодействие с БД или же данное значение является конфигурационным параметром
- Использование же lowerCamelCase указывает на название методов и входных параметров для данного метода.

Дефекта нет.
