### ISSUE TITLE
МкС Authorization. restoreAccessConfirm. Некорректная длина confirmationCode

### ISSUE THREAD

**Issue by Ceparator** [tamagochy/tamagotchi#32]
В запросе к restoreAccessConfirm передается параметр confirmationCode с длинной в 64 (по документации символа).
Например, $2b$04$0XpxgPuQYPNGftMyrzUYJ.V2jZxfKueJU8JFHEtAsDG.w9oHpzOBq

В реализации код генерируется и требуется длиной в 60 символов

Как корректно ?

**Comment by dyshechka** [comment]
@MAKAR1031, помоги пожалуйста разобраться с текущей ситуацией

**Comment by itine** [comment]
попробовал 3 разных .net core'овских, длина получается 60

**Comment by MAKAR1031** [comment]
Думаю, в этом нет ничего критичного, главное, чтобы при восстановлении микросервис смог корректно определить, что коды восстановления совпадают.

**Comment by Ceparator** [comment]
@MAKAR1031 закрываем баг ? МкС работает корректно

**Comment by MAKAR1031** [comment]
Данное поведение корректно. Такой же алгоритм используется при авторизации, если хеши совпадают, то не вижу смысла добавлять требования по длине.
