### ISSUE TITLE
МкС Authorization. Некорректная ошибка несуществующем confirmationCode

### ISSUE THREAD

**Issue by Ceparator** [tamagochy/tamagotchi#33]
Отправить запрос к restoreAccessConfirm, передав несуществующий в БД confirmationCode

ОР:
???
В доке business не уточнен

ФР:
{
    "errors": [
        {
            "code": "business.ConfirmCodeNotFound"
        }
    ]
}

**Comment by itine** [comment]
вопрос к аналитикам

**Comment by dyshechka** [comment]
Можно оставить как есть сейчас.
@Garroshek, внеси пожалуйста изменения в документацию

**Comment by dyshechka** [comment]
В требованиях подобное поведение было расписано

> 5. Выполняется поиск кода подтверждения в таблице CONFIRMATION_CODES по полю CONFIRMATION_CODES.VALUE, используя значение request.body/confirmationCode. (Проверка не выполняется (EC-Business))

Если в требованиях явно не указывается code, значит, по умолчанию используется business.Error
Об этом написано в Общих ошибках.
https://github.com/tamagochy/tamagotchi/wiki/%D0%9E%D0%B1%D1%89%D0%B8%D0%B5-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8#ec-business


@itine, нужно исправить код ошибки

**Comment by itine** [comment]
1.1.1 fixed

**Comment by Ceparator** [comment]
Проверено
