### ISSUE TITLE
МкС Authorization. Некорректная проверка просроченности confirmationCode

### ISSUE THREAD

**Issue by Ceparator** [tamagochy/tamagotchi#34]
Отправить запрос к restoreAccessConfirm, передав в параметрах confirmationCode, причем:
текущее время <= CONFIRMATION_CODES.CREATION_TIME + значение системного параметра CONFIRMATION_CODE_LIFE_TIME

CONFIRMATION_CODE_LIFE_TIME = 300 **секунд**

ОР:
"code": "business.Inactive"

ФР:
Успешный ответ
http://joxi.ru/n2YVvxNHoEk9pA - с учетом того, что в БД разница +3 часа, разница составляет 20 минут, а не 5 минут

**Comment by itine** [comment]
в версии 1.1.0 в docker-compose можно настроить конфиг параметр ConfirmCodeLifeTime. Это CONFIRMATION_CODES.CREATION_TIME в минутах

**Comment by itine** [comment]
1.1.3 fixed

**Comment by Ceparator** [comment]
Проверено
