### ISSUE TITLE
Доработка авторизации с Issuer/Audience. Настройка Middleware-leayer.

### ISSUE THREAD

**Issue by palicpiotr** [tamagochy/tamagotchi#35]
При попытке использовать сгенерированный токен для публичного Action-а прилоежение выкидывает 401 код. 

![image](https://user-images.githubusercontent.com/15847375/49896200-b2d01980-fe63-11e8-9d7f-0aa04784003b.png)

**Comment by palicpiotr** [comment]
Само приложение настроено, чтобы сгенерировать токен по некоторым правилам, но если попытаться повесить атрибут [Authorize] на какой-то открытый Action и указать в хедерах токен, то оно не поймет, что пользователь атворизован и выкинет 401 код. Чтобы исправить это, нужно в middleware слое сконфигурировать схему аутентификации вот так:
```
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer(options =>
            {
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuer = true,
                    ValidateAudience = true,
                    ValidateLifetime = true,
                    ValidateIssuerSigningKey = true,
                    ValidIssuer = "tama.gotchi",
                    ValidAudience = "tama.gotchi",
                    IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(Configuration.GetSection("AppInfo:SecretKey").Value))
                };
            });
```

Здесь также нужно учесть тот факт, что любое другое API не сможет понять, что это за токен пришел, поэтому выкинет 401 код, если не указать ISSUER и AUDIENCE , что соответствует издателю токена и его потребителю, в качестве решения я захардкоженную строку использовал. 
Скорее всего, эти две строки нужно вынести в конфиг.

![image](https://user-images.githubusercontent.com/15847375/49896334-1a866480-fe64-11e8-8f43-0a55fcf79b95.png)

**Comment by MAKAR1031** [comment]
Данная ситуация не является дефектом. Микросервис базовой механики корректно обрабатывает токен, созданный микросервисом авторизации. Также токен проходит валидацию на сайте https://jwt.io/

**Comment by palicpiotr** [comment]
Clear
