### ISSUE TITLE
МкС Competition. Некорректный формат ответа.

### ISSUE THREAD

**Issue by Ceparator** [tamagochy/tamagotchi#37]
Некорректный формат ответа у методов получения текущий версии и текущего счета. На первом рисунке пример ответа getScore
http://joxi.ru/E2p9XqPi9ZEvlA

**Comment by palicpiotr** [comment]
Done. Version: 
palicpiotr/tamagotchi.competition:1.0.8
palicpiotr/tamagotchi.competition:latest

**Comment by MAKAR1031** [comment]
Исправлено
