### ISSUE TITLE
МкС Competition. changeScore. Ошибки при корректном запросе

### ISSUE THREAD

**Issue by Ceparator** [tamagochy/tamagotchi#38]
Вызов метода changeScore возвращает ошибку "protocol.incorrect" при корректном запросе

**Comment by palicpiotr** [comment]
Done. Version: 
palicpiotr/tamagotchi.competition:1.0.8
palicpiotr/tamagotchi.competition:latest

**Comment by MAKAR1031** [comment]
Исправлено
