### ISSUE TITLE
Документ, описывающий базовую механику

### ISSUE THREAD

**Issue by Garroshek** [tamagochy/tamagotchi#4]
https://github.com/tamagochy/tamagotchi/wiki/%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B1%D0%B0%D0%B7%D0%BE%D0%B2%D0%BE%D0%B9-%D0%BC%D0%B5%D1%85%D0%B0%D0%BD%D0%B8%D0%BA%D0%B8

**Comment by dyshechka** [comment]
CLOSE Задача выполнена в версии 1.0.1
