### ISSUE TITLE
МкС Competition. getTopPlayers. Возвращается пустой массив

### ISSUE THREAD

**Issue by Ceparator** [tamagochy/tamagotchi#40]
Отправить запрос к методу getTopPlayers

ОР:
Возвращаются записи из таблицы SCORE с пользователями

ФР:
Пустой массив в ответе

**Comment by palicpiotr** [comment]
Done. Version: 
palicpiotr/tamagotchi.competition:1.0.8
palicpiotr/tamagotchi.competition:latest

**Comment by MAKAR1031** [comment]
Исправлено
