### ISSUE TITLE
МкС Competition. getTopPlayers. Нужна ли сортировка в ответе сервиса ?

### ISSUE THREAD

**Issue by Ceparator** [tamagochy/tamagotchi#41]
Сервис возвращает список логинов и счетов без сортировки, не нужно ли сортировать записи по счетам, например, по убыванию ?

**Comment by Garroshek** [comment]
![image](https://user-images.githubusercontent.com/43106654/50144341-0a391400-02c0-11e9-872a-cb98df9f8356.png)
Товарищи, пожалуйста, обратите внимание на отмеченный фрагмент требований. Выборка из базы осуществляется в порядке по убыванию относительно поля SCORE. Требования составлены корректно, в данном случае необходимо исправление реализации.

**Comment by palicpiotr** [comment]
Сортировка осуществляется в порядке по убыванию относительно св-ва SCORE

**Comment by MAKAR1031** [comment]
Исправлено
